name: Azure java buildpack E2E Test workflow
on:
  release:
    types:
      - published
jobs:
  project-build:
    strategy:
      matrix:
        version: [ 8, 11, 17, 21 ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.version }}
          distribution: 'adopt'

      - name: Set up the Maven dependencies caching
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: package
        run: mvn clean package -DkipTests

      - name: create staging
        run: mkdir -p ${path} && cp target/*.jar ${path}
        env:
          path: java-${{ matrix.version }}

      - uses: actions/upload-artifact@v3
        with:
          name: java${{ matrix.version }}-jar-spring.tar.gz
          path: java-${{ matrix.version }}


